(define (same-parity x . y)
	(define (e y)
			(cond ((null? y) '())
				((even? (car y)) (cons (car y) (e (cdr y))))
				((odd? (car y)) (e (cdr y)))))
	(define (o y)
			(cond ((null? y) '())
				((odd? (car y)) (cons (car y) (o (cdr y))))
				((even? (car y)) (o (cdr y)))))
	(if (even? x)
		(cons x (e y))
		(cons x (o y))))